language: bash

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin
 
script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
      image_name=${image#*/}
      image_name=${image_name%@*}
      docker pull $image
      docker tag $image $DOCKER_REGISTRY/gcr.io/$image_name
      docker push $DOCKER_REGISTRY/gcr.io/$image_name
    done
